name: Docker

on:
  workflow_call: 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: wellingtno96
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
